# https://taskfile.dev
version: '3'
tasks:
  init-counter:
    desc: "create counter demo as https://www.diegofreijo.com/blog/a-gentle-introduction-to-phoenix-liveview-and-tailwind"
    cmds:
    - mix phx.new counter --live

  init-fund:
    desc: "create fund demo as https://earthly.dev/blog/real-time-phoenix-elixir/"
    cmds:
    - mix phx.new --live phoenix_fund