# https://taskfile.dev
version: '3'
vars:
  erlangVersion: "24.2.1"
  elixirVersion: "1.13.2-otp-24"
tasks:
  default:
    cmds:
      - task: test
  sh:
    cmds:
      - iex -S mix
    silent: true
    
  test:
    deps:
      - task: install-deps
    cmds:
      - mix format
      - mix test
      
  install-deps:
    cmds:
      - mix deps.get

  install-hex:
    desc: If we have just installed Elixir for the first time, we will need to install the Hex package manager as well. Hex is necessary to get a Phoenix app running (by installing dependencies) and to install any extra dependencies we might need along the way
    cmds:
      - mix local.hex
      # into ~/.asdf/installs/elixir/1.8.2-otp-21/.mix/archives/
      # ref asdf where elixir

  ###################################################
  #   Setup Env
  setup:
    cmds:
    - task: install-asdf-elixir
    # - task: install-brew-elixir
    - task: version

  version:
    cmds:
      - elixir --version

  # https://elixir-lang.org/install.html
  install-asdf-elixir:
    deps:
      - init-asdf-plugins
    cmds:
      - asdf install erlang {{.erlangVersion}}
      - asdf install elixir {{.elixirVersion}}
      - asdf local elixir {{.elixirVersion}}
      - task: version
  init-asdf-plugins:
    cmds:
      - asdf plugin-add elixir || true
      - asdf plugin-add erlang || true
  set-global-exlixir:
    cmds:
      - asdf global erlang {{.erlangVersion}}
      - asdf global elixir {{.elixirVersion}}

  install-brew-elixir:
    status:
    - which elixir
    cmds:
    - brew install elixir

  ###################################################
  #        Phoenix
  # should have Elixir, Erlang, Hex, and the Phoenix archive installed
  install-phx:
    cmds:
      - mix archive.install hex phx_new 1.4.12

  new-phx:
    cmds:
      - mix phx.new hello-phx --module HelloPhx --app hello_phx --database mysql

  ###################################################
  #        Docker

  dk-pull:
    desc: install as https://hub.docker.com/r/hexpm/elixir/tags?page=1&ordering=name&name=1.13.2-erlang-24.2-al
    cmds:
    - docker pull hexpm/elixir:1.13.2-erlang-24.2-alpine-3.15.0

  dk-sh:
    cmds:
    - docker run -it --rm hexpm/elixir:1.13.2-erlang-24.2-alpine-3.15.0 sh

  ###################################################
  # Elixir & Erlang
  # https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp