# https://taskfile.dev
version: '3'
vars:
  erlangVersion: "24.2.1"
  elixirVersion: "1.13.2-otp-24"
includes:
  phx: Taskfile-phx.yml

tasks:
  default:
    cmds:
      - task: test

  iex: iex

  sh:
    desc: "run into iex session"
    cmds:
      - iex -S mix
    silent: true

  test:
    desc: "run text"
    deps:
      - task: install-deps
    cmds:
      - mix format
      - mix test
  
  init-create:
    cmds:
    - mix new . --module HelloElixir --app hello_elixir --sup

  create-tmp-demo:
    cmds:
    - mix new tmp-demo --module TmpDemo --app tmp_demo --sup

  create-tmp-demo-umb:
    cmds:
    - mix new tmp_demo_umbrella --umbrella

  create-guide-kv:
    desc: create KV as guide
    cmds:
    - mix new kv --module KV --app kv

  create-kv-umbrella:
    desc: create umbrella project as https://elixir-lang.org/getting-started/mix-otp/dependencies-and-umbrella-projects.html#umbrella-projects
    cmds:
    - mix new kv_umbrella --umbrella
  create-kv-server:
    desc: kv server
    cmds:
    - |
      cd kv_umbrella/apps
      mix new kv_server --module KVServer --sup
  
  create-phx-up-and-running:
    desc: create phx up and running as https://hexdocs.pm/phoenix/up_and_running.html
    cmds:
    - mix phx.new phx-up-running --module Hello --app hello
  
  create-ecto-friends:
    desc: create ecto guide project as https://hexdocs.pm/ecto/getting-started.html
    cmds:
    - mix new friends --sup

  create-hello-block:
    desc: try blockchain with elixir
    cmds:
    - mix new hello-block --module HelloBlock --app hello_block --sup

  install-deps:
    desc: "install deps"
    cmds:
      - mix deps.get

  install-hex:
    desc: If we have just installed Elixir for the first time, we will need to install the Hex package manager as well. Hex is necessary to get a Phoenix app running (by installing dependencies) and to install any extra dependencies we might need along the way
    cmds:
      - mix local.hex
      # into ~/.asdf/installs/elixir/1.8.2-otp-21/.mix/archives/
      # ref asdf where elixir

  ###################################################
  #   VsCode 
  # extension: 
  # https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls


  ###################################################
  #   Setup Env
  setup:
    desc: "setup elixir dev env"
    cmds:
    - task: install-asdf-elixir
    # - task: install-brew-elixir
    - task: version

  version:
    desc: "show elixir version"
    cmds:
      - elixir --version

  # https://elixir-lang.org/install.html
  install-asdf-elixir:
    desc: "install elxir by asdf"
    deps:
      - init-asdf-plugins
    cmds:
      - task: install-asdf-erlang
      - asdf install elixir {{.elixirVersion}}
      - asdf local elixir {{.elixirVersion}}
      - task: version

  init-asdf-plugins:
    desc: "init elixir asdf plugin"
    cmds:
      - task: init-asdf-erlang
      - asdf plugin-add elixir || true

  set-global-exlixir:
    desc: "set global elixir version"
    cmds:
      - asdf global erlang {{.erlangVersion}}
      - asdf global elixir {{.elixirVersion}}
  
  install-asdf-erlang:
    desc: "install asdf erlang"
    cmds:
      - task: init-asdf-erlang
      - asdf install erlang {{.erlangVersion}}
  
  init-asdf-erlang:
    desc: "init asdf erlang plugin"
    cmds:
      - asdf plugin-add erlang || true

  install-brew-elixir:
    desc: "install elixir by mac-os brew"
    status:
    - which elixir
    cmds:
    - brew install elixir

  ###################################################
  #        Docker

  dk-pull:
    desc: docker pull image as https://hub.docker.com/r/hexpm/elixir/tags?page=1&ordering=name&name=1.13.2-erlang-24.2-al
    cmds:
    - docker pull hexpm/elixir:1.13.2-erlang-24.2-alpine-3.15.0

  dk-sh:
    desc: "run into docker elixir session"
    cmds:
    - docker run -it --rm hexpm/elixir:1.13.2-erlang-24.2-alpine-3.15.0 iex

  ###################################################
  # Elixir & Erlang
  # https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp