# https://taskfile.dev
version: "3"
vars:
  elixirVersion: "1.17.0-otp-27"
  erlangVersion: "27.0"

tasks:
  default: mix test
  sh: iex --erl "-kernel shell_history enabled" -S mix
  rel: mix release --overwrite --force
  rsh: _build/dev/rel/hello_elixir/bin/hello_elixir start_iex

  # chmod +x run/**/*.exs
  # chmod +x script/**/*.exs
  # iex -S mix test test/hello_elixir_test.exs:6 -b
  slow-test: mix test --slowest 10
  stale-test: mix test --stale
  # https://hexdocs.pm/mix/Mix.Tasks.Test.html#module-file-system-watchers
  smart-test: fswatch lib test | mix test --listen-on-stdin --stale

  mk-hello-elixir:
    cmds:
      - mix new . --module HelloElixir --app hello_elixir --sup

  ###################################################
  #   Setup Env

  install-direnv:
    cmds:
      - brew install direnv

  version:
    desc: "show elixir version"
    cmds:
      - elixir --version

  install-asdf-elixir:
    desc: "install elxir by asdf"
    cmds:
      - task: install-asdf-erlang
      - asdf plugin elixir || true
      - asdf install elixir {{.elixirVersion}}
      - asdf local elixir {{.elixirVersion}}
      - task: version

  install-asdf-erlang:
    desc: "install asdf erlang"
    cmds:
      - asdf plugin erlang || true
      - asdf install erlang {{.erlangVersion}}
