# https://taskfile.dev
version: '3'
tasks:
  default:
    deps:
    - test
    
  test: mix test

  sql:
    cmds:
    - pgcli friends

  sh: iex -S mix

  init:
    desc: setup friends
    cmds:
    - mix deps.get
    - mix ecto.gen.repo -r Friends.Repo
  