# https://taskfile.dev
version: '3'
tasks:
  default: mix test

  sh: iex -S mix

  run: iex -S mix phx.server

  svr: mix phx.server

  db: pgcli hello_dev

  init-postgres-user:
    cmds:
    - echo set password use postgres
    - createuser postgres -s -P
